name: Build and push to Docker Hub
on:
  push:           # we are telling that if any time some one pushes code, please perform the below steps.
    branches:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: kishoremc/docker-cicd:latest1  # Replace with your Docker Hub username and repository
